# Generated by Django 4.2.7 on 2024-02-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='reg',
        ),
    ]
