# Generated by Django 4.2.7 on 2024-02-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_rename_register_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg',
        ),
    ]
