# Generated by Django 4.2.7 on 2024-02-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg',
        ),
    ]
