# Generated by Django 4.2.7 on 2024-02-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layout', '0005_delete_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
