# Generated by Django 4.2.7 on 2024-02-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('URL', models.URLField(max_length=1000)),
            ],
        ),
    ]
