# Generated by Django 4.2.7 on 2024-02-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0007_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Image',
            new_name='Title',
        ),
    ]
