# Generated by Django 4.2.7 on 2024-02-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0008_rename_image_form_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Icon_URL', models.URLField()),
                ('Icon_Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='form',
            name='URL',
            field=models.URLField(),
        ),
    ]
