# Generated by Django 4.2.7 on 2024-02-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0009_form_offer_alter_form_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Image_URL', models.URLField()),
                ('Image_Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
    ]
