# Generated by Django 5.0.1 on 2024-02-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0010_form_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_URL', models.URLField()),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
    ]
