# Generated by Django 5.0.1 on 2024-02-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0011_form_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=255)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
