# Generated by Django 4.2.7 on 2024-03-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0012_form_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=255)),
            ],
        ),
    ]
