# Generated by Django 4.2.7 on 2024-03-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0014_add_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='Default',
            field=models.BooleanField(default=0),
        ),
    ]
