# Generated by Django 4.2.7 on 2024-03-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0019_alter_form_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_offer',
            name='Icon_URL',
        ),
        migrations.AddField(
            model_name='form_offer',
            name='Image',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
