# Generated by Django 4.2.7 on 2024-03-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0020_remove_form_offer_icon_url_form_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_offer',
            name='Image',
            field=models.FileField(default=0, upload_to='media/'),
        ),
    ]
