# Generated by Django 4.2.7 on 2024-03-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0021_alter_form_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_offer',
            name='Image',
            field=models.ImageField(default=0, upload_to='media/'),
        ),
    ]
