# Generated by Django 4.2.7 on 2024-03-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0022_alter_form_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Default',
            field=models.BooleanField(),
        ),
    ]
