# Generated by Django 4.2.7 on 2024-03-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0024_remove_form_photos_image_url_form_photos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_photos',
            name='Image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
