# Generated by Django 4.2.7 on 2024-03-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0026_remove_form_offer_title_remove_form_photos_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_post',
            name='Image_URL',
        ),
        migrations.AddField(
            model_name='form_post',
            name='Image',
            field=models.FileField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
    ]
